package com.bokmcdok.butterflies.common.loot;

import com.google.gson.JsonObject;
import net.minecraft.data.BuiltinRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.minecraftforge.common.loot.GlobalLootModifierSerializer;
import net.minecraftforge.common.loot.LootModifier;
import net.minecraftforge.registries.ForgeRegistries;
import org.jetbrains.annotations.NotNull;

import java.util.List;

/**
 * A loot modifier that adds an item to the loot.
 */
public class AddItemLootModifier extends LootModifier {
    private Item item;

    /**
     * Construction.
     * @param conditionsIn The conditions for this loot modifier.
     * @param item The item to add.
     */
    public AddItemLootModifier(LootItemCondition[] conditionsIn,
                               Item item) {
        super(conditionsIn);
        this.item = item;
    }

    /**
     * Apply the loot modifier.
     * @param generatedLoot The list of ItemStacks that will be dropped, generated by loot tables.
     * @param context The LootContext, identical to what is passed to loot tables.
     * @return The updated list of ItemStacks.
     */
    @NotNull
    @Override
    public List<ItemStack> doApply(List<ItemStack> generatedLoot,
                                   LootContext context) {
        for(LootItemCondition condition : conditions) {
            if(!condition.test(context)) {
                return generatedLoot;
            }
        }

        if (item != null) {
            generatedLoot.add(new ItemStack(item));
        }

        return generatedLoot;
    }

    /**
     * The Loot Modifier Serializer.
     */
    public static class Serializer extends GlobalLootModifierSerializer<AddItemLootModifier> {

        /**
         * Read Loot Modifier data.
         * @param name The resource name.
         * @param object The JSON Object with any extra data.
         * @param conditionsIn The conditions for the loot.
         * @return A new loot modifier.
         */
        @Override
        public AddItemLootModifier read(ResourceLocation name,
                                        JsonObject object,
                                        LootItemCondition[] conditionsIn) {
            return new AddItemLootModifier(conditionsIn);
        }

        /**
         * Write loot modifier data.
         * @param instance The loot modifier.
         * @return Modifier data in JSON format.
         */
        @Override
        public JsonObject write(AddItemLootModifier instance) {
            return makeConditions(instance.conditions);
        }
    }

    /**
     * Used by serializer.
     * @param conditionsIn The conditions for this loot modifier.
     */
    protected AddItemLootModifier(LootItemCondition[] conditionsIn) {
        super(conditionsIn);
    }
}