package com.bokmcdok.butterflies.common.loot;

import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.neoforged.neoforge.common.loot.IGlobalLootModifier;
import net.neoforged.neoforge.common.loot.LootModifier;
import org.jetbrains.annotations.NotNull;

/**
 * A loot modifier that replaces an item in the loot.
 */
public class ReplaceItemLootModifier extends LootModifier {

    public static final MapCodec<ReplaceItemLootModifier> CODEC =
            RecordCodecBuilder.mapCodec(inst ->
                    codecStart(inst)
                            .and(BuiltInRegistries.ITEM.byNameCodec()
                                    .fieldOf("item").forGetter(m -> m.item))
                            .apply(inst, ReplaceItemLootModifier::new));

    private final Item item;

    /**
     * Construction.
     * @param conditionsIn The conditions for this loot modifier.
     * @param item The item to add.
     */
    public ReplaceItemLootModifier(LootItemCondition[] conditionsIn, Item item) {
        super(conditionsIn);
        this.item = item;
    }

    /**
     * Apply the loot modifier.
     * @param generatedLoot The list of ItemStacks that will be dropped, generated by loot tables.
     * @param context The LootContext, identical to what is passed to loot tables.
     * @return The updated list of ItemStacks.
     */
    @Override
    protected @NotNull ObjectArrayList<ItemStack> doApply(@NotNull ObjectArrayList<ItemStack> generatedLoot,
                                                          @NotNull LootContext context) {
        for(LootItemCondition condition : this.conditions) {
            if(!condition.test(context)) {
                return generatedLoot;
            }
        }

        if (item != null) {
            generatedLoot.remove(0);
            generatedLoot.add(new ItemStack(this.item));
        }

        return generatedLoot;
    }

    /**
     * Access to the code.
     * @return The codec.
     */
    @NotNull
    @Override
    public MapCodec<? extends IGlobalLootModifier> codec() {
        return CODEC;
    }
}