package com.bokmcdok.butterflies.world;

/**
 * Generated code - do not modify
 */
public class ButterflyInfo {
    public static final String[] SPECIES = {
            "admiral",
            "bluemoon",
            "buckeye",
            "cabbage",
            "chalkhill",
            "christmas",
            "clipper",
            "clipperblack",
            "clipperblue",
            "clipperbrown",
            "clippercyan",
            "clippergray",
            "clippergreen",
            "clipperlightgray",
            "clipperlime",
            "clippermagenta",
            "clipperorange",
            "clipperpink",
            "clipperpurple",
            "clipperred",
            "clipperwhite",
            "clipperyellow",
            "commander",
            "common-crow",
            "common-mime",
            "common",
            "commonbirdwing",
            "commongrassyellow",
            "emperor",
            "forester",
            "glasswing",
            "green-skirt-baron",
            "hairstreak",
            "heath",
            "longwing",
            "monarch",
            "morpho",
            "peacock",
            "rainbow",
            "swallowtail",
            "bluemoonmale",
            "atlas",
            "carpet",
            "case-bearing-clothes",
            "clothes",
            "codling",
            "diamondback",
            "domestic_silk",
            "hummingbird",
            "indianmeal",
            "luna",
            "oak-silk",
            "peppered",
            "spongy",
            "spongymale",
            "ice",
            "lava",
            "light",
    };

    // A list of traits each butterfly has.
    public static final ButterflyData.Trait[][] TRAITS = {
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
            ButterflyData.Trait.CHRISTMASSY,
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
            ButterflyData.Trait.INEDIBLE,
            ButterflyData.Trait.POISONOUS,
        },
        {
            ButterflyData.Trait.MIMICRY,
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
            ButterflyData.Trait.CATFRIEND,
        },
        {
        },
        {
        },
        {
        },
        {
            ButterflyData.Trait.MOTHWANDERER,
        },
        {
        },
        {
            ButterflyData.Trait.POISONOUS,
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        },
    };
}
